version: "3.9"
services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "1337:1337"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
